-- Database: bst_db

-- DROP DATABASE IF EXISTS bst_db;

CREATE DATABASE bst_db
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;




-- Table: public.tree_record_input_numbers

-- DROP TABLE IF EXISTS public.tree_record_input_numbers;

CREATE TABLE IF NOT EXISTS public.tree_record_input_numbers
(
    tree_record_id bigint NOT NULL,
    input_numbers integer,
    CONSTRAINT fkig23mdylqd006kglib1shqpd3 FOREIGN KEY (tree_record_id)
        REFERENCES public.tree_record (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tree_record_input_numbers
    OWNER to postgres;





-- Table: public.tree_record

-- DROP TABLE IF EXISTS public.tree_record;

CREATE TABLE IF NOT EXISTS public.tree_record
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tree_structure text COLLATE pg_catalog."default",
    CONSTRAINT tree_record_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tree_record
    OWNER to postgres;
